### ISSUE TITLE
Camera 

### ISSUE THREAD

**Issue by Facundojs** [borjanebbal/webrtc-node-app#10]
Hello, im trying to use this project to understand it and apply in other projects.
At the moment to join a room, i get the message
`Could not start video source  ||  client.js:122 `
Looks like `navigator.mediaDevices.getUserMedia(mediaConstraints)` is ever getting catched cause doesnt work
How can i solve that?

**Comment by tql247** [comment]
change
```
const mediaConstraints = {
  audio: true,
  video: { width: 1280, height: 720 },
}
```
to 
```
const mediaConstraints = {
    audio: true,
    video: true,
}
```

**Comment by borjanebbal** [comment]
It's very likely that your browser didn't have permission to access the camera and microphone.

I'm closing the issue since it's from a long time ago. I hope you could fix it and made it work :)
