### ISSUE TITLE
can't connect new user to existing room

### ISSUE THREAD

**Issue by Jenish0dhanani** [borjanebbal/webrtc-node-app#6]
I found that new user can't join existing room because all time value of  numberOfClients=0  in server.js that's why new room created all the time and can't establish connection with existing room. 

if you found proper solution then upload as soon as possible.

Thankyou

**Comment by ruxoft** [comment]
Hi, I changed:
`const roomClients = io.sockets.adapter.rooms[roomId] || { length: 0 }
const numberOfClients = roomClients.length`

to:

`const selectedRoom = io.sockets.adapter.rooms.get(roomId);
const numberOfClients = selectedRoom ? selectedRoom.size : 0;`

in the server.js and it works. Be aware of the socket.io version, I used 4.0.1. Also, the room name cannot be a number.

**Comment by Jenish0dhanani** [comment]
Thank-you very much i created webrtc group video conferencing https://teammeet.infinityfreeapp.com  using webrtc api. Your artical and code very helpful for me. thankyou 🙂
